# Generated by Django 5.1.4 on 2026-05-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=10)),
                ("merchant", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "مطاعم وتوصيل"),
                            ("fuel", "وقود"),
                            ("pharmacy", "صيدليات"),
                            ("shopping", "تسوق"),
                            ("bills", "فواتير وسداد"),
                            ("family", "تحويلات الأهل"),
                            ("bnpl", "تقسيط"),
                            ("investment", "استثمار"),
                            ("salary", "راتب وارد"),
                            ("other", "متنوع"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("raw_sms", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
