# Generated by Django 5.1.4 on 2026-05-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("debit", "خصم"), ("credit", "إيداع")], max_length=10
            ),
        ),
    ]
