# Generated by Django 5.1.4 on 2026-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supermarket", "سوبر ماركت"),
                            ("clothes", "ملابس وخياط"),
                            ("car", "السيارة"),
                            ("food", "مطاعم وتوصيل"),
                            ("pharmacy", "صيدلية"),
                            ("bnpl", "تابي وتمارا"),
                            ("cash", "سحب كاش"),
                            ("family", "تحويل للعائلة"),
                            ("reserve", "سحب من الرصيد الاحتياطي"),
                            ("visa", "تسديد الفيزا"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "monthly_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "حد الميزانية",
                "verbose_name_plural": "حدود الميزانية",
            },
        ),
        migrations.CreateModel(
            name="MerchantRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supermarket", "سوبر ماركت"),
                            ("clothes", "ملابس وخياط"),
                            ("car", "السيارة"),
                            ("food", "مطاعم وتوصيل"),
                            ("pharmacy", "صيدلية"),
                            ("bnpl", "تابي وتمارا"),
                            ("cash", "سحب كاش"),
                            ("family", "تحويل للعائلة"),
                            ("reserve", "سحب من الرصيد الاحتياطي"),
                            ("visa", "تسديد الفيزا"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["merchant"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_categorized",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("supermarket", "سوبر ماركت"),
                    ("clothes", "ملابس وخياط"),
                    ("car", "السيارة"),
                    ("food", "مطاعم وتوصيل"),
                    ("pharmacy", "صيدلية"),
                    ("bnpl", "تابي وتمارا"),
                    ("cash", "سحب كاش"),
                    ("family", "تحويل للعائلة"),
                    ("reserve", "سحب من الرصيد الاحتياطي"),
                    ("visa", "تسديد الفيزا"),
                    ("other", "أخرى"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
