# Generated by Django 5.1.4 on 2026-05-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_categorybudget_merchantrule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "starting_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
