# Generated by Django 5.1.4 on 2026-05-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_merchantmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رصيد الاحتياطي',
                'verbose_name_plural': 'رصيد الاحتياطي',
            },
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve', 'سحب من الرصيد الاحتياطي'), ('reserve_in', 'تحويل للاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve', 'سحب من الرصيد الاحتياطي'), ('reserve_in', 'تحويل للاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], default='other', max_length=50),
        ),
    ]
