# Generated by Django 5.1.4 on 2026-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_reserve_balance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve_in', 'تحويل للاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve_in', 'تحويل للاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], default='other', max_length=50),
        ),
    ]
