# Generated by Django 5.1.4 on 2026-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_reserve_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_claude_parser', models.BooleanField(default=False, help_text='فعّل لاستخدام Claude API بدل الـ Regex Parser', verbose_name='استخدام Claude API للتحليل')),
            ],
            options={
                'verbose_name': 'إعدادات التطبيق',
                'verbose_name_plural': 'إعدادات التطبيق',
            },
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve_in', 'تحويل الى الاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('clothes', 'ملابس وخياط'), ('car', 'السيارة'), ('food', 'مطاعم وتوصيل'), ('pharmacy', 'صيدلية'), ('bnpl', 'تابي وتمارا'), ('cash', 'سحب كاش'), ('family', 'تحويل للعائلة'), ('reserve_in', 'تحويل الى الاحتياطي'), ('reserve_out', 'تحويل من الاحتياطي'), ('visa', 'تسديد الفيزا'), ('maids', 'شغالات'), ('school', 'طلبات مدرسة'), ('laundry', 'مغسلة ملابس'), ('maintenance', 'صيانة البيت')], default='other', max_length=50),
        ),
    ]
