# Generated by Django 5.1.4 on 2026-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_app_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة مخصصة',
                'verbose_name_plural': 'فئات مخصصة',
                'ordering': ['key'],
            },
        ),
    ]
