# Generated by Django 5.1.4 on 2026-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_category_unified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='claude_input_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='claude_output_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorybudget',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantmemory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
